#!/bin/bash
set -e

# Define final output directories
NODE_DIR="packages/node"
WEB_DIR="packages/web"
rm -rf packages/
rm -rf pkg

mkdir -p $NODE_DIR/dist $WEB_DIR/dist pkg

# Build Node.js target
npx wasm-pack build \
  --target nodejs \
  --out-name index \
  --no-default-features \
  --features nodejs
rm -rf pkg/package.json # don't want generated package.json
mv pkg/* $NODE_DIR/dist/
rm -r pkg

# Build web target
npx wasm-pack build \
  --target web \
  --out-name index \
  --no-default-features \
  --features web
rm -rf pkg/package.json # don't want generated package.json
mv pkg/* $WEB_DIR/dist/

cp node_package.json $NODE_DIR/package.json
cp web_package.json $WEB_DIR/package.json

# mv $WEB_DIR/index.js $WEB_DIR/index.mjs
cp src/* $WEB_DIR/dist/
rm -r pkg
