#!/bin/bash
set -e

# Define final output directories
NODE_DIR="dist/node"
WEB_DIR="dist/web"
rm -rf dist
rm -rf pkg

mkdir -p $NODE_DIR $WEB_DIR pkg

# Build Node.js target
npx wasm-pack build \
  --target nodejs \
  --out-name index \
  --no-default-features \
  --features nodejs
rm -rf pkg/package.json # don't want generated package.json
mv pkg/* $NODE_DIR/
mv $NODE_DIR/index.js $NODE_DIR/index.cjs
rm -r pkg

# Build web target
npx wasm-pack build \
  --target web \
  --out-name index \
  --no-default-features \
  --features web
rm -rf pkg/package.json # don't want generated package.json
mv pkg/* $WEB_DIR/
# cp src/opfs.js $WEB_DIR/
rm -r pkg
