projectGroup=tech.turso
projectVersion=0.8.0-pre.10
projectArtifactId=turso

# POM metadata
pomName=Turso JDBC Driver
pomDescription=Turso JDBC driver for Java applications
pomUrl=https://github.com/tursodatabase/turso
pomLicenseName=MIT License
pomLicenseUrl=https://opensource.org/licenses/MIT
pomDeveloperId=turso
pomDeveloperName=Turso
pomDeveloperEmail=penberg@iki.fi
pomScmConnection=scm:git:git://github.com/tursodatabase/turso.git
pomScmDeveloperConnection=scm:git:ssh://github.com:tursodatabase/turso.git
pomScmUrl=https://github.com/tursodatabase/turso