package org.github.tursodatabase.jdbc4;

import org.github.tursodatabase.annotations.SkipNullableCheck;

import java.sql.*;

/**
 * Implementation of the {@link Statement} interface for JDBC 4.
 */
public class JDBC4Statement implements Statement {
    @Override
    @SkipNullableCheck
    public ResultSet executeQuery(String sql) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void close() throws SQLException {
        // TODO
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        // TODO
    }

    @Override
    public int getMaxRows() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        // TODO
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        // TODO
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        // TODO
    }

    @Override
    public void cancel() throws SQLException {
        // TODO
    }

    @Override
    @SkipNullableCheck
    public SQLWarning getWarnings() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        // TODO
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        // TODO
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        // TODO
        return false;
    }

    @Override
    @SkipNullableCheck
    public ResultSet getResultSet() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        // TODO
    }

    @Override
    public int getFetchDirection() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        // TODO
    }

    @Override
    public int getFetchSize() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public int getResultSetType() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        // TODO
    }

    @Override
    public void clearBatch() throws SQLException {
        // TODO
    }

    @Override
    public int[] executeBatch() throws SQLException {
        // TODO
        return new int[0];
    }

    @Override
    @SkipNullableCheck
    public Connection getConnection() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        // TODO
        return false;
    }

    @Override
    @SkipNullableCheck
    public ResultSet getGeneratedKeys() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        // TODO
        return false;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        // TODO
        return false;
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        // TODO
        return false;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public boolean isClosed() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        // TODO
    }

    @Override
    public boolean isPoolable() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        // TODO
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        // TODO
        return false;
    }

    @Override
    @SkipNullableCheck
    public <T> T unwrap(Class<T> iface) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        // TODO
        return false;
    }
}
