package org.github.tursodatabase.jdbc4;

import org.github.tursodatabase.LimboConnection;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class JDBC4Connection extends LimboConnection {

    public JDBC4Connection(String url, String fileName, Properties properties) throws SQLException {
        super(url, fileName, properties);
    }

    @Override
    public Statement createStatement() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        // TODO
        return "";
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        // TODO
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void commit() throws SQLException {
        // TODO
    }

    @Override
    public void rollback() throws SQLException {
        // TODO
    }

    @Override
    public void close() throws SQLException {
        // TODO
    }

    @Override
    public boolean isClosed() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        // TODO
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        // TODO
    }

    @Override
    public String getCatalog() throws SQLException {
        // TODO
        return "";
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        // TODO
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        // TODO
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        // TODO
        return Map.of();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        // TODO
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        // TODO
    }

    @Override
    public int getHoldability() throws SQLException {
        return 0;
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        // TODO
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        // TODO
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Clob createClob() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Blob createBlob() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public NClob createNClob() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        // TODO
        return false;
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        // TODO
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        // TODO
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        // TODO
        return "";
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        // TODO
    }

    @Override
    public String getSchema() throws SQLException {
        // TODO
        return "";
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        // TODO
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        // TODO
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        // TODO
        return 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        // TODO
        return null;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        // TODO
        return false;
    }
}
