/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BatchExecutor {
  /**
   * Step the current statement. Returns `[step, sleepMs]`; `sleepMs` is the
   * delay to wait before stepping again and is nonzero only for `STEP_SLEEP`.
   */
  stepSync(): [number, number]
  reset(): void
}

/** A database connection. */
export declare class Database {
  /**
   * Creates a new database instance.
   *
   * # Arguments
   * * `path` - The path to the database file.
   */
  constructor(path: string, opts?: DatabaseOpts | undefined | null)
  /**
   * Connect the database synchronously
   * This method is idempotent and can be called multiple times safely until the database will be closed
   */
  connectSync(): void
  /**
   * Connect the database asynchronously
   * This method is idempotent and can be called multiple times safely until the database will be closed
   */
  connectAsync(): Promise<void>
  /** Returns whether the database is in readonly-only mode. */
  get readonly(): boolean
  /** Returns whether the database is in memory-only mode. */
  get memory(): boolean
  /** Returns whether the database is in memory-only mode. */
  get path(): string
  /** Returns whether the database connection is open. */
  get open(): boolean
  /**
   * Prepares a statement for execution.
   *
   * # Arguments
   *
   * * `sql` - The SQL statement to prepare.
   *
   * # Returns
   *
   * A promise resolving to a `Statement` instance.
   */
  prepare(sql: string): Promise<Statement>
  executor(sql: string, queryOptions?: QueryOptions | undefined | null): BatchExecutor
  /**
   * Returns the rowid of the last row inserted.
   *
   * # Returns
   *
   * The rowid of the last row inserted.
   */
  lastInsertRowid(): number
  /**
   * Returns the number of changes made by the last statement.
   *
   * # Returns
   *
   * The number of changes made by the last statement.
   */
  changes(): number
  /**
   * Returns the total number of changes made by all statements.
   *
   * # Returns
   *
   * The total number of changes made by all statements.
   */
  totalChanges(): number
  /**
   * Returns whether the connection is currently inside a transaction.
   *
   * This is the inverse of `sqlite3_get_autocommit()`: a connection in
   * autocommit mode is not in a transaction. It reflects the connection's
   * real state, including transactions opened with a raw `BEGIN`.
   *
   * # Returns
   *
   * `true` if a transaction is open, `false` if in autocommit mode.
   */
  inTransaction(): boolean
  /**
   * Closes the database connection.
   *
   * # Returns
   *
   * `Ok(())` if the database is closed successfully.
   */
  close(): void
  /**
   * Sets the default safe integers mode for all statements from this database.
   *
   * # Arguments
   *
   * * `toggle` - Whether to use safe integers by default.
   */
  defaultSafeIntegers(toggle?: boolean | undefined | null): void
  /** Runs the I/O loop synchronously. */
  ioLoopSync(): void
  /** Runs the I/O loop asynchronously, returning a Promise. */
  ioLoopAsync(): Promise<void>
  /** Classify SQL statement. Returns "read", "write", "begin", "commit", or "rollback". */
  classifySql(sql: string): string
}

/** A prepared statement. */
export declare class Statement {
  reset(): void
  setQueryTimeout(queryOptions?: QueryOptions | undefined | null): void
  /** Returns the number of parameters in the statement. */
  parameterCount(): number
  /**
   * Returns the name of a parameter at a specific 1-based index.
   *
   * # Arguments
   *
   * * `index` - The 1-based parameter index.
   */
  parameterName(index: number): string | null
  /**
   * Binds a parameter at a specific 1-based index with explicit type.
   *
   * # Arguments
   *
   * * `index` - The 1-based parameter index.
   * * `value_type` - The type constant (0=null, 1=int, 2=float, 3=text, 4=blob).
   * * `value` - The value to bind.
   */
  bindAt(index: number, value: unknown): void
  /**
   * Step the statement (executed on the main thread). Returns `[step, sleepMs]`
   * where `step` is 1 = Row available, 2 = Done, 3 = I/O needed, 4 = Sleep
   * requested, and `sleepMs` is the delay to wait before stepping again
   * (nonzero only for `STEP_SLEEP`).
   */
  stepSync(): [number, number]
  /** Get the current row data according to the presentation mode */
  row(): unknown
  /** Sets the presentation mode to raw. */
  raw(raw?: boolean | undefined | null): void
  /** Sets the presentation mode to pluck. */
  pluck(pluck?: boolean | undefined | null): void
  /**
   * Sets safe integers mode for this statement.
   *
   * # Arguments
   *
   * * `toggle` - Whether to use safe integers.
   */
  safeIntegers(toggle?: boolean | undefined | null): void
  /** Get column information for the statement */
  columns(): Promise<TableColumn[]>
  /** Finalizes the statement. */
  finalize(): void
}

/**
 * Most of the options are aligned with better-sqlite API
 * (see https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#new-databasepath-options)
 */
export interface DatabaseOpts {
  readonly?: boolean
  timeout?: number
  defaultQueryTimeout?: number
  fileMustExist?: boolean
  tracing?: string
  /** Experimental features to enable */
  experimental?: Array<string>
  /** Optional encryption configuration for local database encryption */
  encryption?: EncryptionOpts
}

/** Supported encryption ciphers for local database encryption. */
export declare const enum EncryptionCipher {
  Aes128Gcm = 0,
  Aes256Gcm = 1,
  Aegis256 = 2,
  Aegis256x2 = 3,
  Aegis128l = 4,
  Aegis128x2 = 5,
  Aegis128x4 = 6
}

/** Encryption configuration for local database encryption. */
export interface EncryptionOpts {
  /** The cipher to use for encryption */
  cipher: EncryptionCipher
  /** The hex-encoded encryption key */
  hexkey: string
}

export interface QueryOptions {
  queryTimeout?: number
}

export interface TableColumn {
  name: string
  type?: string | null
  column?: undefined
  table?: undefined
  database?: undefined
}
export declare class GeneratorHolder {
  resumeSync(error?: string | undefined | null): GeneratorResponse
  resumeAsync(error?: string | undefined | null): Promise<unknown>
}

export declare class JsDataCompletion {
  poison(err: string): void
  status(value: number): void
  pushBuffer(value: Buffer): void
  pushTransform(values: Array<DatabaseRowTransformResultJs>): void
  done(): void
}

export declare class JsProtocolIo {

}

export declare class JsProtocolRequestBytes {
  request(): JsProtocolRequest
  completion(): JsDataCompletion
}

export declare class SyncEngine {
  constructor(opts: SyncEngineOpts)
  connect(): GeneratorHolder
  ioLoopSync(): void
  /** Runs the I/O loop asynchronously, returning a Promise. */
  ioLoopAsync(): Promise<void>
  protocolIo(): JsProtocolRequestBytes | null
  protocolIoStep(): void
  push(): GeneratorHolder
  stats(): GeneratorHolder
  wait(): GeneratorHolder
  apply(changes: SyncEngineChanges): GeneratorHolder
  checkpoint(): GeneratorHolder
  db(): Database
  close(): void
}

export declare class SyncEngineChanges {
  empty(): boolean
}

export declare const enum DatabaseChangeTypeJs {
  Insert = 'insert',
  Update = 'update',
  Delete = 'delete'
}

export interface DatabaseRowMutationJs {
  changeTime: number
  tableName: string
  id: number
  changeType: DatabaseChangeTypeJs
  before?: Record<string, any>
  after?: Record<string, any>
  updates?: Record<string, any>
}

export interface DatabaseRowStatementJs {
  sql: string
  values: Array<any>
}

export type DatabaseRowTransformResultJs =
  | { type: 'Keep' }
  | { type: 'Skip' }
  | { type: 'Rewrite', stmt: DatabaseRowStatementJs }

export type GeneratorResponse =
  | { type: 'IO' }
  | { type: 'Done' }
  | { type: 'SyncEngineStats', cdcOperations: number, mainWalSize: number, revertWalSize: number, lastPullUnixTime?: number, lastPushUnixTime?: number, revision?: string, networkSentBytes: number, networkReceivedBytes: number }
  | { type: 'SyncEngineChanges', changes: SyncEngineChanges }

export type JsPartialBootstrapStrategy =
  | { type: 'Prefix', length: number }
  | { type: 'Query', query: string }

export interface JsPartialSyncOpts {
  bootstrapStrategy: JsPartialBootstrapStrategy
  segmentSize?: number
  prefetch?: boolean
}

export type JsProtocolRequest =
  | { type: 'Http', url?: string, method: string, path: string, body?: Uint8Array, headers: Array<[string, string]> }
  | { type: 'FullRead', path: string }
  | { type: 'FullWrite', path: string, content: Uint8Array }
  | { type: 'Transform', mutations: Array<DatabaseRowMutationJs> }

export interface SyncEngineOpts {
  path: string
  remoteUrl?: string
  clientName?: string
  walPullBatchSize?: number
  longPollTimeoutMs?: number
  tracing?: string
  tablesIgnore?: Array<string>
  useTransform: boolean
  protocolVersion?: SyncEngineProtocolVersion
  bootstrapIfEmpty: boolean
  /**
   * Experimental features to enable on the local database (e.g. "views",
   * "index_method", "vacuum"). Mirrors the `experimental` option of the
   * non-sync `Database`.
   */
  experimental?: Array<string>
  /** Encryption cipher for the Turso Cloud database. */
  remoteEncryptionCipher?: string
  /**
   * Base64-encoded encryption key for the Turso Cloud database.
   * Must match the key used when creating the encrypted database.
   */
  remoteEncryptionKey?: string
  partialSyncOpts?: JsPartialSyncOpts
  /**
   * Optional cap on the number of CDC operations packed into a single push
   * batch. When set, push splits on transaction boundaries once the batch
   * has accumulated at least this many operations. `None` (default) sends
   * the entire change set in one batch.
   */
  pushOperationsThreshold?: number
  /**
   * Optional hint, in bytes, that splits the bootstrap download into
   * multiple `/pull-updates` HTTP requests of >= this many bytes each.
   * `None` (default) bootstraps in a single round-trip. No-op when
   * partial-sync uses the query bootstrap strategy.
   */
  pullBytesThreshold?: number
  /**
   * Sync-protocol override for incremental pulls. Unset (default)
   * auto-detects the remote protocol from the first pull-updates response;
   * `true` forces MVCC logical-log streams; `false` forces page streams.
   */
  logicalMvccPull?: boolean
}

export declare const enum SyncEngineProtocolVersion {
  Legacy = 'legacy',
  V1 = 'v1'
}
