<Project>
  <PropertyGroup>
    <Version>0.8.0-pre.10</Version>
    <TursoPackageVersion>$(Version)</TursoPackageVersion>
    <TursoTargetFrameworks>net8.0;net9.0;net10.0</TursoTargetFrameworks>
    <Company>Turso</Company>
    <Product>Turso</Product>
    <Copyright>Copyright (c) 2026 Turso</Copyright>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
